name: Deploy Biblioteca App to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore, Build and Publish
      run: |
        dotnet restore
        dotnet build -c Release --no-restore
        dotnet publish -c Release -o published --no-build

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BibliotecaWeb'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: published

    - name: Configure Application Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: 'BibliotecaWeb'
        app-settings: |
          [
            {
              "name": "ConnectionStrings__DefaultConnection",
              "value": "${{ secrets.DB_CONNECTION_STRING }}",
              "slotSetting": false
            },
            {
              "name": "ASPNETCORE_ENVIRONMENT",
              "value": "Production",
              "slotSetting": false
            }
          ]
