name: Deploy Biblioteca App to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore, Build and Publish
      run: |
        dotnet restore
        dotnet build -c Release --no-restore
        dotnet publish -c Release -o published --no-build

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BibliotecaWeb'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: published

    - name: Configure Application Settings
      run: |
        az webapp config appsettings set --name BibliotecaWeb --resource-group Biblioteca --settings ASPNETCORE_ENVIRONMENT=Production
        az webapp config connection-string set --name BibliotecaWeb --resource-group Biblioteca --connection-string-type SQLAzure --settings DefaultConnection="${{ secrets.DB_CONNECTION_STRING }}"
